name: Build and Package for Release

on:
  release:
    types: [created]

jobs:
  build-linux:
    name: Build DEB & RPM Packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from Cargo.toml
        id: extract_version
        run: |
          VERSION=$(grep '^version' Cargo.toml | head -n 1 | cut -d '"' -f2)
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Install packaging tools and deps
        run: |
          sudo apt-get update
          sudo apt-get install -y devscripts debhelper rpm build-essential \
          libglib2.0-dev pkg-config libgirepository1.0-dev
          
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build binary
        run: cargo build --release

      - name: Package as .tar.gz
        run: |
          mkdir -p dist
          cp target/release/xdg-mimer dist/
          tar -czvf dist/xdg-mimer-${{ env.VERSION }}-linux.tar.gz -C dist xdg-mimer

      # ----- DEB BUILD -----
      - name: Prepare Debian changelog
        run: |
          cp -r debian debuild/
          cp -r * debuild/
          cd debuild
          echo "xdg-mimer ($VERSION) unstable; urgency=medium" > debian/changelog
          echo "" >> debian/changelog
          echo "  * Auto-generated release." >> debian/changelog
          echo "" >> debian/changelog
          echo " -- GitHub Actions <no-reply@github.com>  $(date -R)" >> debian/changelog

      - name: Build .deb
        run: |
          cd debuild
          dpkg-buildpackage -us -uc
          cd ..
          mv *.deb dist/

      # ----- RPM BUILD -----
      - name: Prepare RPM sources
        run: |
          sed "s/^Version:.*/Version:        $VERSION/" xdg-mimer.spec > updated.spec
          mkdir -p rpmbuild/SOURCES
          tar czf rpmbuild/SOURCES/xdg-mimer-$VERSION.tar.gz --transform "s,^,xdg-mimer-$VERSION/," .
          mv updated.spec xdg-mimer.spec

      - name: Build .rpm
        run: |
          rpmbuild -ba xdg-mimer.spec --define "_topdir $(pwd)/rpmbuild"
          cp rpmbuild/RPMS/x86_64/*.rpm dist/

      # ----- Upload -----
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
  build-arch:
    name: Build Arch Package
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      
    steps:
      - uses: actions/checkout@v4
      - name: Extract version from Cargo.toml
        id: extract_version
        run: |
          VERSION=$(grep '^version' Cargo.toml | head -n 1 | cut -d '"' -f2)
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        
      - name: Replace version in PKGBUILD
        run: sed -i "s/@VERSION@/${{ env.VERSION }}/g" PKGBUILD

      - name: Prepare build environment
        run: |
          pacman -Syu --noconfirm
          useradd -m builder
          chown -R builder .
          su builder -c "makepkg -si --noconfirm"

      - name: Upload .pkg.tar.zst
        uses: softprops/action-gh-release@v1
        with:
          files: ./*.pkg.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
